apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trailblazer-ai

resources:
  - ../../base

images:
  - name: trailblazer-ai
    newName: trailblazeraicr.azurecr.io/trailblazer-ai
    newTag: latest

patches:
  - path: ingress-patch.yaml
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: secrets-patch.yaml

commonLabels:
  environment: aks
  cloud: azure
