apiVersion: v1
kind: Service
metadata:
  name: trailblazer-ai
  namespace: trailblazer-ai
  labels:
    app.kubernetes.io/name: trailblazer-ai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trailblazer-ai
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
